# Generated by Django 2.1.7 on 2019-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeaddr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeaddr',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
