# Generated by Django 2.1.7 on 2019-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fenster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenster_width', models.IntegerField()),
                ('window_view', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
