# Generated by Django 2.1.7 on 2019-04-19 12:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0003_fenster_fenster_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='fenster_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
