# Generated by Django 2.1.7 on 2019-04-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
