# Generated by Django 2.1.7 on 2019-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0007_apartament'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='fenster_apartament',
            field=models.ManyToManyField(to='fenster.Apartament'),
        ),
    ]
